# Generated by Django 3.0.3 on 2020-04-23 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server_list', '0002_commandlog_instype_serverlist_servernamerule_serverpid'),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakLogSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=40, verbose_name='服务器名称')),
                ('max_player', models.CharField(max_length=40, verbose_name='在线人数/最大人数')),
                ('cpu', models.CharField(max_length=40, verbose_name='CPU占用率')),
                ('memory', models.CharField(max_length=40, verbose_name='内存占用')),
                ('send_flow', models.CharField(max_length=80, verbose_name='发送流量占用')),
                ('recv_flow', models.CharField(max_length=80, verbose_name='接收流量占用')),
                ('version', models.CharField(max_length=40, verbose_name='版本')),
                ('zone', models.CharField(max_length=20, verbose_name='地区')),
                ('plat', models.CharField(max_length=20, verbose_name='平台')),
                ('run_company', models.CharField(max_length=40, verbose_name='运行商')),
                ('ip', models.CharField(max_length=50, verbose_name='ip地址')),
                ('user', models.CharField(max_length=20, verbose_name='用户')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='日期')),
                ('server_rule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_list.ServerNameRule', verbose_name='崩溃日志查询_服务器名称规则id')),
            ],
            options={
                'verbose_name': '崩溃日志查询',
                'verbose_name_plural': '崩溃日志查询',
                'db_table': 'zero_break_log_search',
            },
        ),
    ]
