# Generated by Django 3.0.3 on 2020-03-12 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_break_log_search'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='break_log_search',
            new_name='BreakLogSearch',
        ),
    ]
