# Generated by Django 3.0.3 on 2020-04-23 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_breaklogsearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breaklogsearch',
            old_name='server_rule_id',
            new_name='server_rule',
        ),
    ]
