# Generated by Django 3.0.3 on 2020-03-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20200312_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaklogsearch',
            name='version',
            field=models.CharField(max_length=40, verbose_name='版本'),
        ),
    ]
