# Generated by Django 3.0.3 on 2020-03-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20200316_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaklogsearch',
            name='cpu',
            field=models.CharField(default='', max_length=40, verbose_name='CPU占用率'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breaklogsearch',
            name='max_player',
            field=models.CharField(default='', max_length=40, verbose_name='在线人数/最大人数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breaklogsearch',
            name='memory',
            field=models.CharField(default='', max_length=40, verbose_name='内存占用'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breaklogsearch',
            name='recv_flow',
            field=models.CharField(default='', max_length=80, verbose_name='接收流量占用'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breaklogsearch',
            name='send_flow',
            field=models.CharField(default='', max_length=80, verbose_name='发送流量占用'),
            preserve_default=False,
        ),
    ]
