# Generated by Django 3.0.3 on 2020-03-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20200316_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaklogsearch',
            name='ip',
            field=models.CharField(max_length=50, verbose_name='ip地址'),
        ),
    ]
