# Generated by Django 3.0.3 on 2020-03-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=40, verbose_name='账户名称')),
                ('account_id', models.CharField(max_length=50, verbose_name='账户id')),
                ('account_key', models.CharField(max_length=50, verbose_name='账户key')),
            ],
            options={
                'verbose_name': '云账户表',
                'verbose_name_plural': '云账户表',
                'db_table': 'zero_cloud_user',
            },
        ),
    ]
