# Generated by Django 3.0.3 on 2020-05-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountzone',
            name='account_name',
            field=models.CharField(max_length=40, verbose_name='账户名称'),
        ),
    ]
