# Generated by Django 3.0.3 on 2020-03-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='zone',
            field=models.CharField(max_length=50, null=True, verbose_name='地区'),
        ),
    ]
