# Generated by Django 3.0.3 on 2020-04-23 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cloud_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=40, unique=True, verbose_name='账户名称')),
                ('account_id', models.CharField(max_length=50, verbose_name='账户id')),
                ('account_key', models.CharField(max_length=50, verbose_name='账户key')),
            ],
            options={
                'verbose_name': '云账户表',
                'verbose_name_plural': '云账户表',
                'db_table': 'zero_cloud_user',
            },
        ),
        migrations.CreateModel(
            name='ZoneCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=60, verbose_name='区域中文')),
                ('code', models.CharField(max_length=60, verbose_name='区域代码')),
            ],
            options={
                'verbose_name': '可用区代码表',
                'verbose_name_plural': '可用区代码表',
                'db_table': 'zero_zone_code',
            },
        ),
        migrations.CreateModel(
            name='AccountZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=40, verbose_name='账户名称')),
                ('account_id', models.CharField(max_length=50, verbose_name='账户id')),
                ('account_key', models.CharField(max_length=50, verbose_name='账户key')),
                ('region', models.CharField(max_length=1024, null=True, verbose_name='可用区')),
                ('cloud_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_user.Account', verbose_name='账户可用区_账户名称id')),
            ],
            options={
                'verbose_name': '账户可用区表',
                'verbose_name_plural': '账户可用区表',
                'db_table': 'zero_account_zone',
            },
        ),
        migrations.CreateModel(
            name='ServerAccountZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=40, verbose_name='账户名称')),
                ('zone', models.CharField(max_length=60, verbose_name='可新增服务器地区')),
                ('cloud_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_user.Account', verbose_name='可新增服务器地区_账户名称id')),
            ],
            options={
                'verbose_name': '可新增服务器地区表',
                'verbose_name_plural': '可新增服务器地区表',
                'db_table': 'zero_server_account_zone',
                'unique_together': {('account_name', 'zone')},
            },
        ),
    ]
