# Generated by Django 3.0.3 on 2020-03-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_user', '0002_account_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=40, verbose_name='账户名称')),
                ('account_id', models.CharField(max_length=50, verbose_name='账户id')),
                ('account_key', models.CharField(max_length=50, verbose_name='账户key')),
                ('available_zone', models.CharField(max_length=1024, null=True, verbose_name='可用区')),
            ],
            options={
                'verbose_name': '账户可用区表',
                'verbose_name_plural': '账户可用区表',
                'db_table': 'zero_account_zone',
            },
        ),
    ]
