# Generated by Django 3.0.3 on 2020-04-23 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_user', '0002_account_accountzone_serveraccountzone_zonecode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountzone',
            old_name='cloud_user_id',
            new_name='cloud_user',
        ),
        migrations.RenameField(
            model_name='serveraccountzone',
            old_name='cloud_user_id',
            new_name='cloud_user',
        ),
    ]
