# Generated by Django 3.0.3 on 2020-03-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_user', '0003_account_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='zone_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=60, verbose_name='区域中文')),
                ('code', models.CharField(max_length=60, verbose_name='区域代码')),
            ],
            options={
                'verbose_name': '可用区代码表',
                'verbose_name_plural': '可用区代码表',
                'db_table': 'zero_zone_code',
            },
        ),
    ]
