# Generated by Django 3.0.3 on 2020-03-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_user', '0004_zone_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='server_account_zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=40, verbose_name='账户名称')),
                ('zone', models.CharField(max_length=60, verbose_name='可新增服务器地区')),
            ],
            options={
                'verbose_name': '可新增服务器地区表',
                'verbose_name_plural': '可新增服务器地区表',
                'db_table': 'zero_server_account_zone',
            },
        ),
        migrations.RemoveField(
            model_name='account',
            name='zone',
        ),
    ]
