# Generated by Django 3.0.3 on 2020-03-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_user', '0005_auto_20200310_1412'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='server_account_zone',
            unique_together={('account_name', 'zone')},
        ),
    ]
