# Generated by Django 3.0.3 on 2020-03-12 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_user', '0007_auto_20200311_2112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account_zone',
            new_name='AccountZone',
        ),
        migrations.RenameModel(
            old_name='server_account_zone',
            new_name='ServerAccountZone',
        ),
        migrations.RenameModel(
            old_name='zone_code',
            new_name='ZoneCode',
        ),
    ]
