# Generated by Django 3.0.3 on 2020-03-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_type', models.CharField(max_length=40, verbose_name='实例类型')),
                ('pattern_name', models.CharField(max_length=40, verbose_name='模式名称')),
                ('player_num', models.IntegerField(default=1000, verbose_name='单台实例分配在线人数')),
                ('cpu_num', models.IntegerField(default=2, verbose_name='单台实例分配CPU')),
                ('memory_num', models.IntegerField(default=500, verbose_name='单台实例分配内存')),
                ('flow_num', models.IntegerField(default=1000, verbose_name='单台实例分配流量')),
            ],
            options={
                'verbose_name': '模式配置表',
                'verbose_name_plural': '模式配置表',
                'db_table': 'zero_pattern',
            },
        ),
        migrations.CreateModel(
            name='run_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_company_name', models.CharField(max_length=40, verbose_name='运营商名称')),
            ],
            options={
                'verbose_name': '运营商配置表',
                'verbose_name_plural': '运营商配置表',
                'db_table': 'zero_run_company',
            },
        ),
        migrations.CreateModel(
            name='version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename_uuid', models.CharField(max_length=32, verbose_name='文件名_uuid')),
                ('filename', models.CharField(max_length=40, verbose_name='上传文件名')),
                ('version', models.CharField(max_length=10, verbose_name='版本号')),
                ('server_name', models.CharField(max_length=40, verbose_name='服务器名称')),
            ],
            options={
                'verbose_name': '文件名版本表',
                'verbose_name_plural': '文件名版本表',
                'db_table': 'zero_version',
            },
        ),
    ]
