# Generated by Django 3.0.3 on 2020-04-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40, unique=True, verbose_name='版本号')),
                ('plat', models.CharField(max_length=20, verbose_name='平台')),
            ],
            options={
                'verbose_name': '可新增版本表',
                'verbose_name_plural': '可新增版本表',
                'db_table': 'zero_add_version',
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_type', models.CharField(max_length=40, verbose_name='实例类型')),
                ('pay_type', models.CharField(max_length=20, verbose_name='付费类型')),
                ('pattern', models.CharField(max_length=40, unique=True, verbose_name='模式名称')),
                ('player_num', models.IntegerField(default=1000, verbose_name='单台实例分配在线人数')),
                ('cpu_num', models.IntegerField(default=2, verbose_name='单台实例分配CPU')),
                ('memory_num', models.IntegerField(default=2, verbose_name='单台实例分配内存')),
                ('disk_num', models.IntegerField(default=20, verbose_name='单台实例分配硬盘')),
                ('flow_num', models.IntegerField(default=2, verbose_name='单台实例分配流量')),
            ],
            options={
                'verbose_name': '模式配置表',
                'verbose_name_plural': '模式配置表',
                'db_table': 'zero_pattern',
            },
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat', models.CharField(max_length=40, unique=True, verbose_name='平台')),
            ],
            options={
                'verbose_name': '平台配置表',
                'verbose_name_plural': '平台配置表',
                'db_table': 'zero_plat',
            },
        ),
        migrations.CreateModel(
            name='RunCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_company_name', models.CharField(max_length=40, unique=True, verbose_name='运营商名称')),
            ],
            options={
                'verbose_name': '运营商配置表',
                'verbose_name_plural': '运营商配置表',
                'db_table': 'zero_run_company',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename_uuid', models.CharField(max_length=32, verbose_name='文件名_uuid')),
                ('version', models.CharField(max_length=40, unique=True, verbose_name='版本号')),
                ('server_name', models.CharField(max_length=40, verbose_name='服务器名称')),
                ('pattern', models.CharField(max_length=40, verbose_name='模式')),
                ('zone', models.CharField(max_length=20, verbose_name='地区')),
                ('run_company', models.CharField(max_length=40, verbose_name='运营商')),
            ],
            options={
                'verbose_name': '文件名版本表',
                'verbose_name_plural': '文件名版本表',
                'db_table': 'zero_version',
            },
        ),
    ]
