# Generated by Django 3.0.3 on 2020-05-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_addversion_pattern_plat_runcompany_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='server_name',
            field=models.CharField(max_length=40, unique=True, verbose_name='服务器名称'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version',
            field=models.CharField(max_length=40, verbose_name='版本号'),
        ),
    ]
