# Generated by Django 3.0.3 on 2020-03-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20200306_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=40, verbose_name='上传文件名')),
                ('version', models.CharField(max_length=40, verbose_name='版本号')),
            ],
            options={
                'verbose_name': '可新增版本表',
                'verbose_name_plural': '可新增版本表',
                'db_table': 'zero_add_version',
            },
        ),
    ]
