# Generated by Django 3.0.3 on 2020-03-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_add_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='pattern',
            field=models.CharField(default='', max_length=40, verbose_name='模式'),
            preserve_default=False,
        ),
    ]
