# Generated by Django 3.0.3 on 2020-03-12 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_auto_20200311_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_version',
            new_name='AddVersion',
        ),
        migrations.RenameModel(
            old_name='run_company',
            new_name='RunCompany',
        ),
    ]
