# Generated by Django 3.0.3 on 2020-03-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20200312_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='id',
        ),
        migrations.AlterField(
            model_name='pattern',
            name='pattern',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='模式名称'),
        ),
    ]
