# Generated by Django 3.0.3 on 2020-03-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_auto_20200312_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='run_company',
            field=models.CharField(default='', max_length=40, verbose_name='运营商'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='zone',
            field=models.CharField(default='', max_length=20, verbose_name='地区'),
            preserve_default=False,
        ),
    ]
