# Generated by Django 3.0.3 on 2020-03-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_auto_20200312_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='addversion',
            name='run_company',
            field=models.CharField(default='', max_length=40, verbose_name='运营商名称'),
            preserve_default=False,
        ),
    ]
