# Generated by Django 3.0.3 on 2020-03-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_addversion_run_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addversion',
            name='run_company',
        ),
        migrations.AddField(
            model_name='addversion',
            name='plat',
            field=models.CharField(default='', max_length=20, verbose_name='平台'),
            preserve_default=False,
        ),
    ]
