# Generated by Django 3.0.3 on 2020-03-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_auto_20200312_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat', models.CharField(max_length=40, verbose_name='平台')),
            ],
            options={
                'verbose_name': '平台配置表',
                'verbose_name_plural': '平台配置表',
                'db_table': 'zero_plat',
            },
        ),
    ]
