# Generated by Django 3.0.3 on 2020-03-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_plat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addversion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='plat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='runcompany',
            name='id',
        ),
        migrations.RemoveField(
            model_name='version',
            name='id',
        ),
        migrations.AddField(
            model_name='pattern',
            name='pay_type',
            field=models.CharField(default='', max_length=20, verbose_name='付费类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addversion',
            name='version',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='plat',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='runcompany',
            name='run_company_name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='运营商名称'),
        ),
        migrations.AlterField(
            model_name='version',
            name='server_name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='服务器名称'),
        ),
    ]
