# Generated by Django 3.0.3 on 2020-03-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_auto_20200314_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='disk_num',
            field=models.IntegerField(default=20, verbose_name='单台实例分配硬盘'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='flow_num',
            field=models.IntegerField(default=2, verbose_name='单台实例分配流量'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='memory_num',
            field=models.IntegerField(default=2, verbose_name='单台实例分配内存'),
        ),
    ]
