# Generated by Django 3.0.3 on 2020-03-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=40, verbose_name='服务器名称')),
                ('send_command', models.CharField(max_length=40, verbose_name='命令内容')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '命令日志表',
                'verbose_name_plural': '命令日志表',
                'db_table': 'zero_command_log',
            },
        ),
        migrations.CreateModel(
            name='InsType',
            fields=[
                ('ins_type', models.CharField(max_length=40, verbose_name='实例类型')),
                ('ip', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ip地址')),
                ('account_name', models.CharField(max_length=40, verbose_name='账户名称')),
            ],
            options={
                'verbose_name': '实例类型表',
                'verbose_name_plural': '实例类型表',
                'db_table': 'zero_ins_type',
            },
        ),
        migrations.CreateModel(
            name='ServerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=40, verbose_name='服务器名称')),
                ('max_player', models.CharField(max_length=40, verbose_name='在线人数/最大人数')),
                ('cpu', models.CharField(max_length=40, verbose_name='CPU占用率')),
                ('memory', models.CharField(max_length=40, verbose_name='内存占用')),
                ('send_flow', models.CharField(max_length=80, verbose_name='发送流量占用')),
                ('recv_flow', models.CharField(max_length=80, verbose_name='接收流量占用')),
                ('version', models.CharField(max_length=40, verbose_name='版本')),
                ('pattern', models.CharField(max_length=20, verbose_name='模式')),
                ('zone', models.CharField(max_length=20, verbose_name='地区')),
                ('plat', models.CharField(max_length=20, verbose_name='平台')),
                ('run_company', models.CharField(max_length=40, verbose_name='运行商')),
                ('ip', models.CharField(max_length=20, verbose_name='ip地址')),
                ('user', models.CharField(max_length=20, verbose_name='用户')),
                ('port', models.CharField(max_length=20, verbose_name='端口')),
                ('instance_name', models.CharField(max_length=40, null=True, verbose_name='实例名称')),
                ('account', models.CharField(max_length=40, verbose_name='账户')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='日期')),
                ('is_activate', models.IntegerField(default=0, verbose_name='服务器状态')),
            ],
            options={
                'verbose_name': '服务器列表',
                'verbose_name_plural': '服务器列表',
                'db_table': 'zero_server_list',
            },
        ),
        migrations.CreateModel(
            name='ServerListUpdate',
            fields=[
                ('server_name', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='服务器名称')),
                ('max_player', models.CharField(max_length=40, verbose_name='在线人数/最大人数')),
                ('cpu', models.CharField(max_length=40, verbose_name='CPU占用率')),
                ('memory', models.CharField(max_length=40, verbose_name='内存占用')),
                ('send_flow', models.CharField(max_length=80, verbose_name='发送流量占用')),
                ('recv_flow', models.CharField(max_length=80, verbose_name='接收流量占用')),
                ('version', models.CharField(max_length=40, verbose_name='版本')),
                ('pattern', models.CharField(max_length=20, verbose_name='模式')),
                ('zone', models.CharField(max_length=20, verbose_name='地区')),
                ('plat', models.CharField(max_length=20, verbose_name='平台')),
                ('run_company', models.CharField(max_length=40, verbose_name='运行商')),
                ('ip', models.CharField(max_length=20, verbose_name='ip地址')),
                ('user', models.CharField(max_length=20, verbose_name='用户')),
                ('port', models.CharField(max_length=20, verbose_name='端口')),
                ('instance_name', models.CharField(max_length=40, null=True, verbose_name='实例名称')),
                ('account', models.CharField(max_length=40, verbose_name='账户')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='日期')),
                ('is_activate', models.IntegerField(default=0, verbose_name='服务器状态')),
            ],
            options={
                'verbose_name': '服务器最新状态表',
                'verbose_name_plural': '服务器最新状态表',
                'db_table': 'zero_server_list_update',
            },
        ),
        migrations.CreateModel(
            name='ServerPid',
            fields=[
                ('server_name', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='服务器名称')),
                ('pid', models.CharField(max_length=10, verbose_name='服务器进程号')),
                ('ip', models.CharField(max_length=20, verbose_name='ip地址')),
                ('user', models.CharField(max_length=20, verbose_name='用户')),
            ],
            options={
                'verbose_name': '服务器进程pid表',
                'verbose_name_plural': '服务器进程pid表',
                'db_table': 'zero_server_pid',
            },
        ),
    ]
