# Generated by Django 3.0.3 on 2020-03-17 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommandLog',
        ),
    ]
