# Generated by Django 3.0.3 on 2020-04-23 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0002_commandlog_instype_serverlist_servernamerule_serverpid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandlog',
            old_name='server_rule_id',
            new_name='server_rule',
        ),
        migrations.RenameField(
            model_name='serverlist',
            old_name='server_rule_id',
            new_name='server_rule',
        ),
        migrations.RenameField(
            model_name='serverpid',
            old_name='server_rule_id',
            new_name='server_rule',
        ),
    ]
