# Generated by Django 3.0.3 on 2020-03-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0002_delete_commandlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=40, verbose_name='服务器名称')),
                ('send_command', models.CharField(max_length=40, verbose_name='命令内容')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '命令日志表',
                'verbose_name_plural': '命令日志表',
                'db_table': 'zero_command_log',
            },
        ),
    ]
