# Generated by Django 3.0.3 on 2020-03-17 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0003_commandlog'),
    ]

    operations = [
    ]
