# Generated by Django 3.0.3 on 2020-04-25 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0004_serverlistupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverlistupdate',
            old_name='instance_name',
            new_name='instance_id',
        ),
    ]
