# Generated by Django 3.0.3 on 2020-03-17 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0004_auto_20200317_0950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommandLog',
        ),
    ]
