# Generated by Django 3.0.3 on 2020-04-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0005_auto_20200425_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='cpu',
            field=models.FloatField(default=0.0, verbose_name='CPU占用率'),
        ),
        migrations.AlterField(
            model_name='serverlist',
            name='memory',
            field=models.FloatField(default=0.0, verbose_name='内存占用'),
        ),
        migrations.AlterField(
            model_name='serverlist',
            name='recv_flow',
            field=models.FloatField(default=0.0, verbose_name='接收流量占用'),
        ),
        migrations.AlterField(
            model_name='serverlist',
            name='send_flow',
            field=models.FloatField(default=0.0, verbose_name='发送流量占用'),
        ),
        migrations.AlterField(
            model_name='serverlistupdate',
            name='cpu',
            field=models.FloatField(default=0.0, verbose_name='CPU占用率'),
        ),
        migrations.AlterField(
            model_name='serverlistupdate',
            name='memory',
            field=models.FloatField(default=0.0, verbose_name='内存占用'),
        ),
        migrations.AlterField(
            model_name='serverlistupdate',
            name='recv_flow',
            field=models.FloatField(default=0.0, verbose_name='接收流量占用'),
        ),
        migrations.AlterField(
            model_name='serverlistupdate',
            name='send_flow',
            field=models.FloatField(default=0.0, verbose_name='发送流量占用'),
        ),
    ]
