# Generated by Django 3.0.3 on 2020-03-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0006_commandlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerNameRule',
            fields=[
                ('server_name', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='服务器名称')),
                ('zone', models.CharField(max_length=20, verbose_name='地区')),
                ('num', models.IntegerField(default=0, verbose_name='序号')),
            ],
            options={
                'verbose_name': '服务器名称规则表',
                'verbose_name_plural': '服务器名称规则表',
                'db_table': 'zero_server_name_rule',
            },
        ),
    ]
