# Generated by Django 3.0.3 on 2020-03-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0007_servernamerule'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverpid',
            name='flag',
            field=models.IntegerField(default=1, verbose_name='异常标志'),
        ),
    ]
