# Generated by Django 3.0.3 on 2020-04-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0007_auto_20200430_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='日期'),
        ),
    ]
