# Generated by Django 3.0.3 on 2020-03-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0008_serverpid_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instype',
            name='ip',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ip地址'),
        ),
        migrations.AlterField(
            model_name='serverlist',
            name='instance_name',
            field=models.CharField(max_length=50, null=True, verbose_name='实例名称'),
        ),
        migrations.AlterField(
            model_name='serverlist',
            name='ip',
            field=models.CharField(max_length=50, verbose_name='ip地址'),
        ),
        migrations.AlterField(
            model_name='serverlistupdate',
            name='instance_name',
            field=models.CharField(max_length=50, null=True, verbose_name='实例名称'),
        ),
        migrations.AlterField(
            model_name='serverlistupdate',
            name='ip',
            field=models.CharField(max_length=50, verbose_name='ip地址'),
        ),
        migrations.AlterField(
            model_name='serverpid',
            name='ip',
            field=models.CharField(max_length=50, verbose_name='ip地址'),
        ),
    ]
