# Generated by Django 3.0.3 on 2020-04-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_list', '0009_auto_20200320_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='server_name',
            field=models.CharField(db_index=True, max_length=40, verbose_name='服务器名称'),
        ),
    ]
